[general]
connection = "Host=localhost;Database=line-equipment-backup;Username=line-equipment-backup;Password=line-equipment-backup;Include Error Detail=true"
output = "DataAccess\\Schema.fs"
namespace = "Delving.API.DataAccess.Schema"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "Npgsql.NpgsqlDataReader"
[filters]
include = []
exclude = []
